[package]
name = "pino_async"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["MrPicklePinosaur"]
description = "simple rust asynchronous runtime"
repository = "https://github.com/MrPicklePinosaur/pino_async"
